mock_provider "aws" {}
mock_provider "helm" {}

# The IRSA role ARN is generated by the mocked AWS provider, so it is unknown
# during plan and would make every assertion on the rendered values unknown
# too. Pinning it here keeps the assertions deterministic and tests what this
# module actually decides: that the annotation is present and carries the role.
override_module {
  target = module.irsa
  outputs = {
    role_arn                = "arn:aws:iam::123456789012:role/role-obs-platform-prod-observability-alb-controller"
    role_name               = "role-obs-platform-prod-observability-alb-controller"
    assume_role_policy_json = "{}"
  }
}

variables {
  cluster_name       = "obs-platform-prod-observability"
  vpc_id             = "vpc-0bbbbbbbbbbbbbbbb"
  region             = "eu-west-1"
  oidc_provider_arn  = "arn:aws:iam::123456789012:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/EXAMPLE"
  oidc_provider_host = "oidc.eks.eu-west-1.amazonaws.com/id/EXAMPLE"
  chart_repository   = "oci://123456789012.dkr.ecr.eu-west-1.amazonaws.com/charts"
  chart_version      = "1.13.4"
  image_repository   = "123456789012.dkr.ecr.eu-west-1.amazonaws.com/mirror/eks/aws-load-balancer-controller"
  image_tag          = "v2.13.4"
}

run "values_pin_the_cluster_vpc_and_region" {
  command = plan

  assert {
    condition     = output.values.clusterName == "obs-platform-prod-observability"
    error_message = "The controller refuses to start without the exact cluster name."
  }

  assert {
    condition     = output.values.vpcId == "vpc-0bbbbbbbbbbbbbbbb"
    error_message = "Pinning vpcId saves the controller an IMDS lookup and makes the plan self-documenting."
  }
}

run "image_comes_from_ecr_not_upstream" {
  command = plan

  assert {
    condition     = strcontains(output.rendered_values, "123456789012.dkr.ecr.eu-west-1.amazonaws.com/mirror/eks/aws-load-balancer-controller")
    error_message = "ADR 0005 forbids pulling from a public registry at deploy time."
  }

  assert {
    condition     = !strcontains(output.rendered_values, "public.ecr.aws")
    error_message = "No upstream registry may appear in the rendered values."
  }
}

run "webhook_certificate_does_not_depend_on_cert_manager" {
  command = plan

  assert {
    condition     = output.values.enableCertManager == false
    error_message = "The chart must self-sign its webhook certificate. Depending on cert-manager here creates a deploy-order cycle, since cert-manager's own webhook needs a working cluster."
  }
}

run "service_account_is_annotated_with_the_irsa_role" {
  command = plan

  assert {
    condition     = output.values.serviceAccount.annotations["eks.amazonaws.com/role-arn"] != ""
    error_message = "Without the role-arn annotation the controller falls back to the node role and cannot create load balancers."
  }

  assert {
    condition     = output.service_account_name == "aws-load-balancer-controller"
    error_message = "The ServiceAccount name is pinned in the IRSA trust policy and must not drift."
  }
}

run "inline_policy_fits_within_the_iam_limit" {
  command = plan

  # AWS caps an inline role policy at 10,240 characters. The vendored upstream
  # document is kept pretty-printed for review and compacted before it is sent,
  # which is what buys the headroom for upstream to add statements.
  assert {
    condition     = length(output.inline_policy_json) < 10240
    error_message = "The compacted policy exceeds IAM's 10,240-character inline limit. Split it into a customer managed policy."
  }

  assert {
    condition     = length(output.inline_policy_json) < length(file("${path.module}/iam-policy.json"))
    error_message = "The policy must be compacted before it is sent, or the pretty-printed whitespace eats the headroom."
  }
}

run "release_is_pinned_and_does_not_create_its_namespace" {
  command = plan

  assert {
    condition     = helm_release.this.version == "1.13.4"
    error_message = "Chart version must be pinned, never floating."
  }

  assert {
    condition     = helm_release.this.create_namespace == false
    error_message = "Terraform owns namespaces; charts never create them."
  }
}
